### ISSUE TITLE
docker-compose setup for demo

### ISSUE THREAD

**Issue by brenzi** [capsule-corp-ternoa/sgx-keyvault#10]
including
* ternoa chain: one node in `--dev --tmp` mode
* N instances of KeyVault runnong in `SGX_MODE=SW`
* client running demo script #9

**Comment by haerdib** [comment]
See https://github.com/integritee-network/worker/tree/master/local-setup for a possible automatic set up

**Comment by echevrier** [comment]
I tried with docker-composer, but I could not find out why the connection between the node and the worker does not work. This solution should work, but we need more time to find the problem. Code in demo-setup
Marcel Frei advised me to create the demo in a single container. Code in demo-keyvault

**Comment by echevrier** [comment]
The docker checkout the branch `add-skip-ra-feature` from `ternoa/chain` to run with skip-ra

**Comment by echevrier** [comment]
The demo in one container seems to have the same problem: I get
`[2021-07-30T18:54:35Z ERROR ws::handler] WS Error <Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })>`
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Disconnected(RecvError)', worker/src/main.rs:302:10`

**Comment by haerdib** [comment]
I think it doesn't make sense to waste much more time on docker-compose. Instead I'll integrate the already exising python script from integritee-worker:  https://github.com/integritee-network/worker/tree/master/local-setup . We only need to run one docker there, and not multiple.. no need for docker-compose..
