### ISSUE TITLE
[client] implement aes256 file encryption

### ISSUE THREAD

**Issue by brenzi** [capsule-corp-ternoa/sgx-keyvault#2]
1. generate a random encryption key and write it to a file
2. encrypt input file into outputfile

according to #1

**Comment by haerdib** [comment]
An example of Aes key generation can be found here:
https://github.com/capsule-corp-ternoa/sgx-keyvault/blob/master/enclave/src/aes.rs
However, keep in mind, that this is implemented within the enclave (= no-std environment). Hence, if you find something overcomplicated there, don't hesistate to use the simpler way for the client implementation.

More information on the aes crate can be found here:
https://crates.io/crates/aes

The AES key will be stored locally, without passphrase protection.

**Comment by haerdib** [comment]
For starters, I'd suggest to create a new folder within the [stf folder](https://github.com/capsule-corp-ternoa/sgx-keyvault/tree/master/stf/src) and a create new file which handles the local key file(s). For example: sgx-keyvault/stf/src/cli_utils/aes.rs (or whatever name is suitable).

Maybe it would make sense to wrap the new function(s) within a struct?

**Comment by haerdib** [comment]
The MVP is a function with:
```
INPUT: <inputfile>
OUTPUT: - or Result<..>
# create inputfile.cyphertext and inputfile.aes256 with the symmetric key
```

**Comment by haerdib** [comment]
EDIT: In spite of what I've written above, we should implement this function within the [client folder](https://github.com/capsule-corp-ternoa/sgx-keyvault/tree/develop/client/src), not the stf folder. See issue #1 for more details.
