### ISSUE TITLE
[client + keyvault]  get-nft-registry RPC call

### ISSUE THREAD

**Issue by haerdib** [capsule-corp-ternoa/sgx-keyvault#26]
Add `get-nft-registry` RPC call for easy debugging (check if enclave has really synced with NFTRegistry of node)

**Comment by haerdib** [comment]
@brenzi this call is purely used for debugging purpose. Should it still be implemented as TrustedCall (resp TrustedGetter?) and be encrypted?

**Comment by brenzi** [comment]
just pick the easiest way to implement it. It might - however - not only be needed for debugging, but verification in general
