### ISSUE TITLE
[client] implement NFT pallet interaction

### ISSUE THREAD

**Issue by brenzi** [capsule-corp-ternoa/sgx-keyvault#3]
according to calls regarding NFT defined in #1 

interact with 
https://github.com/capsule-corp-ternoa/chain/tree/main/pallets/nfts

NFT properties are defined here:
https://github.com/capsule-corp-ternoa/chain/blob/2a3085a4cb612c461f746ab09a4ef5a2714f44a0/pallets/nfts/src/types.rs#L13

The only changing field in the NFT for this demo is offchain_uri:
* offchain_uri: for this demo, this will just be the local filename of the capsule cyphertext
* series_id: hardcoded to 1u32
* is_capsule: true

We just create a new NFT and listen for the `created` event to extract and return the NFTid
https://github.com/capsule-corp-ternoa/chain/blob/2a3085a4cb612c461f746ab09a4ef5a2714f44a0/pallets/nfts/src/lib.rs#L200

**Comment by brenzi** [comment]
that is a question for @ETeissonniere I think.

**Comment by echevrier** [comment]
@ETeissonniere has confirmed. The default serie id is 0. I change the code according to it.
