### ISSUE TITLE
[client] keyvault interaction

### ISSUE THREAD

**Issue by brenzi** [capsule-corp-ternoa/sgx-keyvault#4]
according to #1

For simplicity `keyvault list` returns all urls registered in the enclave registry, without checking MRENCLAVE

# `keyvault provision`

1. read aes256 key from file
2. M = number of lines in urllist
3. N = arg
4. shamir split aes256 key into M shares, of which any N are needed for key recovery (consider https://crates.io/crates/sharks)
5. for all urls in list
   a. send ith share to url_i
   b. verify availability

## edge cases
url may not be responsive -> ignore for now

# `keyvault check`

query keyvault if single share for NFTid is in store

# `keyvault get`

query single key share

**Comment by haerdib** [comment]
EDIT: 4: shamir split aes256 key into M shares, of which any **N** are needed for key recovery

**Comment by haerdib** [comment]
@brenzi: `keyvault list` is within the keyvault section, but it actually does not interact with the keyvault .. or does it?
I've understood the ` keyvault list` more like a differently named [ `list-workers` ](https://github.com/integritee-network/worker/blob/master/client/src/main.rs#L294-L317).

**Comment by haerdib** [comment]
To read aes256 key from file an extra input (file name ) for provision call is needed on client side.
