### ISSUE TITLE
Permission Issue with SGX Key Vault build file after a network outage

### ISSUE THREAD

**Issue by gokulsan** [capsule-corp-ternoa/sgx-keyvault#54]
Hello Team,

During the SGX Key Vault Setup process, there was an internet outage. When I restarted the build process from the same docker instance, it is behaving quite erratic. Hence it is a bit doubtful if the SGX keyvault is crash fault tolerant or Byzantine Fault Tolerant in the current setup. Please find the error messages from the make build process. Looking forward to your support. 

 Updating git repository `https://github.com/capsule-corp-ternoa/chain`
    Updating git repository `https://github.com/scs/substrate-api-client`
    Updating git repository `https://github.com/scs/sgx-runtime`
  Downloaded openssl-sys v0.9.65
  Downloaded aes v0.3.2
  Downloaded block-cipher-trait v0.6.2
  Downloaded aes-soft v0.3.3
  Downloaded openssl v0.10.35
  Downloaded stream-cipher v0.3.2
  Downloaded ofb v0.1.1
  Downloaded sharks v0.5.0
  Downloaded 8 crates (475.8 KB) in 13.79s
error: Permission denied (os error 13) at path "/home/semiott/Apps/tnoa_apps/demo/sgx-keyvault/targetlji8t6"
make: *** [Makefile:179: bin/ternoa-client] Error 101

**Comment by haerdib** [comment]
Could you please run a "make clean" and see it this helps?

**Comment by gokulsan** [comment]
Thank you so much for the recommendations. The clean up instructions in the README.md worked.
