### ISSUE TITLE
[keyvault] extend RPC functions

### ISSUE THREAD

**Issue by brenzi** [capsule-corp-ternoa/sgx-keyvault#6]
Add the following direct `TrustedCalls`

Requirements:
* all TrustedCalls are authenticated and encrypted
* response must later be encrpyted. for now, we return key shares in plaintext, assuming wss:// will do the encryption (a single keyvault learning a key share is considered a minor risk - for now)

rpc calls
* `provision(owner, NFTid, share)` -> returns `Result`
* `check(owner, NFTid)` -> returns bool
* `get(owner, NFTid)` -> returns `Some(key_share)`

**Comment by brenzi** [comment]
@haerdib I guess this should be based on the sidechain-direct-rpc because we have direct invocation of encrypted TrustedCalls but without any sidechain block-production and no need for top-pool because the order of handling calls doesn't matter. agreed?

**Comment by haerdib** [comment]
Are there no shards / states involved? Or where does the enclave look up the requested information?

**Comment by haerdib** [comment]
Edit: I just looked through the other issues and think I've got the big picture now. Yes, I agree. A top-pool does not seem to be necessary and in my opinion there is no reason not using the already implemented rpc interface.

**Comment by haerdib** [comment]
@brenzi the MRENCLAVE will not be checked at all for keyvault rpc calls, is this is correct?

**Comment by haerdib** [comment]
@brenzi  according to #1 the call `check` does not need an owner. Which one is the valid version?

**Comment by brenzi** [comment]
usually, the client would add the expected MRENCLAVE to the signature payload such that the signature of the TrustedCall or TrustedGetterSigned is only valid if the MRENCLAVE matches

**Comment by brenzi** [comment]
> @brenzi according to #1 the call `check` does not need an owner. Which one is the valid version?
> 
> also, Should "Check" and "Get" really be trustedcalls or rather trusted getters?

check, get are TrustedGetterSigned. need to be authenticated

**Comment by haerdib** [comment]
> usually, the client would add the expected MRENCLAVE to the signature payload such that the signature of the TrustedCall or TrustedGetterSigned is only valid if the MRENCLAVE matches

I agree. As we are currently working with possibly different MRENCLAVEs of the registered keyvault, it then would make sense to store the MRENCLAVE to the keyvault-list where the urls are stored. This way the provisioning call can get the keyvault address including the assosciated MRENCLAVE directly from the file.

Or do you see an other way to get the valid MRENCLAVE @brenzi ?

**Comment by haerdib** [comment]
As written in issue #8 :

> The RPC Interface ( issue #6 ) will take care of:
> 
>     * decryption/decoding
> 
>     * MRENCLAVE verification
> 
>     * Response parsing, including the signing of the response
> 
>     * calling the Keyvault Storage only with a valid (expected) `TrustedCall` / `TrustedGetter`
> 
>     * verify signature of `TrustedXXXSigned`
>       Reasoning: These actiosn are not keyvault specific, they should be done for all incoming RPC calls.
>
