### ISSUE TITLE
[keyvault] store and load keyshare

### ISSUE THREAD

**Issue by brenzi** [capsule-corp-ternoa/sgx-keyvault#8]
upon `provision`call, store share on disk in sealed file using SgxFs. 
* Filename should encode the NFTID
* contents must be verifiable, so sign it with enclave signing key
* (optional, needs more thought) replay-attack resistance: also store block number at the time of provisioning
* call shall be blocking

unseal upon `check` or `get`
* verify signature

**Comment by haerdib** [comment]
Keyvault must check if the user is the owner of the queried shamir key respective the NFTid (in the local nft registry)
(Authorization)

**Comment by haerdib** [comment]
I think it would make sense here to create a separate struct handling the Keyshare interactions.
I'm thinking about something like:
```rust
pub struct KeyvaultStorage { } // not sure if it needs any parameters

impl KeyvaultStorage {
    pub provision(.....) -> ... {
        // do provision logic
     }

    pub check(...) -> ... { }

    pub get(...) -> ... { }
}

```

SgxFs interaction is already implemented here: https://github.com/capsule-corp-ternoa/sgx-keyvault/blob/master/enclave/src/io.rs
I think you should be able to reuse this within this struct. And if not, it's a good example for SgxFs interaction.

**Comment by haerdib** [comment]
@brenzi , you've explicitely written verify Signature here. Is it not enough to decrypt it? Is signature still necessary?

**Comment by haerdib** [comment]
@brenzi also, according to #1 the call `check` does not need an owner. Which one is the valid version?

**Comment by brenzi** [comment]
> @brenzi , you've explicitely written to verify signature here. Is it not enough to simply decrypt it?

The `check` and `get` must be authenticated, the keystore will be authenticated anyway if we use sgxfs to stor the stuff on disk. there, decryption is enough

**Comment by haerdib** [comment]
> The `check` and `get` must be authenticated, the keystore will be authenticated anyway if we use sgxfs to store the stuff on disk. there, decryption is enough

Then I'd suggest the following task splitting:
The RPC Interface (issue #6) will take care of:
- decryption/decoding
-  MRENCLAVE verification
-  Response parsing, including the signing of the response
- calling the Keyvault Storage only with a valid (expected) `TrustedCall` / `TrustedOperation`
-  verify signature of `TrustedXXXSigned`
Reasoning: These actiosn are not keyvault specific, they should be done for all incoming RPC calls.

And the keyvault (this issue) will take care of:
- authenticate owner (by calling the NFT registry, issue #7)
- SgxFs interaction

@brenzi do you agree?

**Comment by echevrier** [comment]
Authorization are still on TODO. waiting for #7

**Comment by echevrier** [comment]
For now Share are Vec<u8>. @haerdib will check if it is really not possible to import crate sharks::Share
