### ISSUE TITLE
demo script for success&adversary scenario

### ISSUE THREAD

**Issue by brenzi** [capsule-corp-ternoa/sgx-keyvault#9]
bash or python script using our CLI

1. Alice creates a capsule
2. Alice transfers ownership to Bob
3. Bob opens Capsule successfully

Adversary scenario 1:
1. Alice creates a capsule
2. Bob fails to retrieve key shares from keyvault because he's not he owner of the NFT

Adversary scenario 2:
1. Alice registers an NFT but stops before provisioning key shards to keyvaults
3. Bob fails to provision key shards because he's not the owner

**Comment by haerdib** [comment]
This issue includes the final end2end test of our implementations. Just posting it so we don't forget to include this in our time estimation.

**Comment by haerdib** [comment]
Similar scripts are writtin in bash can be found here: https://github.com/capsule-corp-ternoa/sgx-keyvault/blob/master/client/demo_shielding_unshielding.sh

or in python: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/client/polkadex_commands.py and https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/client/polkadex_demo_happy_flow.py

respective more complicated examples that include the worker & node start up: https://github.com/integritee-network/worker/tree/master/local-setup
